export type ThemePalette = {
  // Primary
  primary: string;
  onPrimary: string;
  primaryContainer: string;
  onPrimaryContainer: string;
  primaryFixed: string;
  primaryFixedDim: string;
  // Secondary
  secondary: string;
  onSecondary: string;
  secondaryContainer: string;
  onSecondaryContainer: string;
  // Tertiary
  tertiary: string;
  onTertiary: string;
  tertiaryContainer: string;
  onTertiaryContainer: string;
  // Surface
  background: string;
  surface: string;
  surfaceDim: string;
  surfaceContainerLow: string;
  surfaceContainer: string;
  surfaceContainerHigh: string;
  surfaceContainerHighest: string;
  // On-surface
  onSurface: string;
  onSurfaceVariant: string;
  // Outline
  outline: string;
  outlineVariant: string;
  // Error
  error: string;
  onError: string;
  // Neo-brutalist border
  border: string;
};

export type ThemeName =
  | 'brasa'
  | 'negroni'
  | 'guayaba'
  | 'mezcal'
  | 'ultravioleta'
  | 'calle'
  | 'fresaPicante'
  | 'mangoOscuro'
  | 'tamarindo'
  | 'aguacate'
  | 'cafe'
  | 'oceano';

export const THEMES: Record<ThemeName, ThemePalette> = {
  brasa: {
    primary: '#c03a00',
    onPrimary: '#ffffff',
    primaryContainer: '#ff6b35',
    onPrimaryContainer: '#5a1800',
    primaryFixed: '#ffddd1',
    primaryFixedDim: '#ffb59e',
    secondary: '#005f53',
    onSecondary: '#ffffff',
    secondaryContainer: '#00d4b8',
    onSecondaryContainer: '#003d35',
    tertiary: '#6f5092',
    onTertiary: '#ffffff',
    tertiaryContainer: '#a584ca',
    onTertiaryContainer: '#391b5a',
    background: '#fdf7f5',
    surface: '#fdf7f5',
    surfaceDim: '#dcd9d9',
    surfaceContainerLow: '#f7f3f1',
    surfaceContainer: '#f1eeec',
    surfaceContainerHigh: '#ebe8e6',
    surfaceContainerHighest: '#e5e2e0',
    onSurface: '#1c1b1b',
    onSurfaceVariant: '#5b4038',
    outline: '#8f7067',
    outlineVariant: '#e4beb3',
    error: '#ba1a1a',
    onError: '#ffffff',
    border: '#1c1b1b',
  },

  negroni: {
    primary: '#c44b00',
    onPrimary: '#ffffff',
    primaryContainer: '#ff7c38',
    onPrimaryContainer: '#4a1800',
    primaryFixed: '#ffddd0',
    primaryFixedDim: '#ffb090',
    secondary: '#1a1008',
    onSecondary: '#ffffff',
    secondaryContainer: '#2e2016',
    onSecondaryContainer: '#ff7c38',
    tertiary: '#c9a227',
    onTertiary: '#2a1e00',
    tertiaryContainer: '#e8c84a',
    onTertiaryContainer: '#2a1e00',
    background: '#fdf6ee',
    surface: '#fdf6ee',
    surfaceDim: '#ddd8d0',
    surfaceContainerLow: '#f8f2e8',
    surfaceContainer: '#f2ece0',
    surfaceContainerHigh: '#ece6d8',
    surfaceContainerHighest: '#e6e0d0',
    onSurface: '#1c1b1b',
    onSurfaceVariant: '#4a3828',
    outline: '#7a6050',
    outlineVariant: '#d4c0a8',
    error: '#ba1a1a',
    onError: '#ffffff',
    border: '#1c1b1b',
  },

  guayaba: {
    primary: '#e8325a',
    onPrimary: '#ffffff',
    primaryContainer: '#ff8fa8',
    onPrimaryContainer: '#5a0018',
    primaryFixed: '#ffd6e0',
    primaryFixedDim: '#ffacc0',
    secondary: '#0d5c6e',
    onSecondary: '#ffffff',
    secondaryContainer: '#30c4d8',
    onSecondaryContainer: '#002830',
    tertiary: '#c0004a',
    onTertiary: '#ffffff',
    tertiaryContainer: '#ff6b90',
    onTertiaryContainer: '#460018',
    background: '#fff5f7',
    surface: '#fff5f7',
    surfaceDim: '#e0d4d8',
    surfaceContainerLow: '#faf0f2',
    surfaceContainer: '#f4e8ec',
    surfaceContainerHigh: '#eee0e5',
    surfaceContainerHighest: '#e8d8de',
    onSurface: '#1c1b1b',
    onSurfaceVariant: '#501828',
    outline: '#804858',
    outlineVariant: '#e0b0c0',
    error: '#ba1a1a',
    onError: '#ffffff',
    border: '#1c1b1b',
  },

  mezcal: {
    primary: '#9c5a00',
    onPrimary: '#ffffff',
    primaryContainer: '#f0a030',
    onPrimaryContainer: '#3a1e00',
    primaryFixed: '#ffe8b8',
    primaryFixedDim: '#f0c870',
    secondary: '#3d6b2a',
    onSecondary: '#ffffff',
    secondaryContainer: '#8dc870',
    onSecondaryContainer: '#152600',
    tertiary: '#7a5200',
    onTertiary: '#ffffff',
    tertiaryContainer: '#d4a830',
    onTertiaryContainer: '#2a1a00',
    background: '#fdf8ee',
    surface: '#fdf8ee',
    surfaceDim: '#ddd8c8',
    surfaceContainerLow: '#f8f3e4',
    surfaceContainer: '#f2edda',
    surfaceContainerHigh: '#ece7d0',
    surfaceContainerHighest: '#e6e1c8',
    onSurface: '#1c1b1b',
    onSurfaceVariant: '#4a3818',
    outline: '#7a6040',
    outlineVariant: '#d4c098',
    error: '#ba1a1a',
    onError: '#ffffff',
    border: '#1c1b1b',
  },

  ultravioleta: {
    primary: '#3d00cc',
    onPrimary: '#ffffff',
    primaryContainer: '#8c66ff',
    onPrimaryContainer: '#0d0033',
    primaryFixed: '#e0d4ff',
    primaryFixedDim: '#b899ff',
    secondary: '#cc4400',
    onSecondary: '#ffffff',
    secondaryContainer: '#ff8c42',
    onSecondaryContainer: '#3d1000',
    tertiary: '#6633cc',
    onTertiary: '#ffffff',
    tertiaryContainer: '#c4a8ff',
    onTertiaryContainer: '#1a0050',
    background: '#f8f5ff',
    surface: '#f8f5ff',
    surfaceDim: '#dcd8e8',
    surfaceContainerLow: '#f3f0fc',
    surfaceContainer: '#edeaf8',
    surfaceContainerHigh: '#e7e3f4',
    surfaceContainerHighest: '#e1ddf0',
    onSurface: '#1c1b1b',
    onSurfaceVariant: '#3a2860',
    outline: '#6650a0',
    outlineVariant: '#cac0e8',
    error: '#ba1a1a',
    onError: '#ffffff',
    border: '#1c1b1b',
  },

  calle: {
    primary: '#c9a800',
    onPrimary: '#1a1500',
    primaryContainer: '#e8c830',
    onPrimaryContainer: '#1a1500',
    primaryFixed: '#fff9c4',
    primaryFixedDim: '#fff176',
    secondary: '#1a1a2e',
    onSecondary: '#ffffff',
    secondaryContainer: '#2d2d4a',
    onSecondaryContainer: '#c9c9ff',
    tertiary: '#c0001c',
    onTertiary: '#ffffff',
    tertiaryContainer: '#e94560',
    onTertiaryContainer: '#ffffff',
    background: '#f8f5e8',
    surface: '#f8f5e8',
    surfaceDim: '#dedad0',
    surfaceContainerLow: '#f4f1e2',
    surfaceContainer: '#eeebd8',
    surfaceContainerHigh: '#e8e5ce',
    surfaceContainerHighest: '#e2dfc8',
    onSurface: '#1c1b1b',
    onSurfaceVariant: '#4a4830',
    outline: '#7a7850',
    outlineVariant: '#d4d0a8',
    error: '#ba1a1a',
    onError: '#ffffff',
    border: '#1c1b1b',
  },

  fresaPicante: {
    primary: '#d4004c',
    onPrimary: '#ffffff',
    primaryContainer: '#ff5c8a',
    onPrimaryContainer: '#5a0018',
    primaryFixed: '#ffd6e4',
    primaryFixedDim: '#ffacc8',
    secondary: '#5a8c00',
    onSecondary: '#ffffff',
    secondaryContainer: '#b8f000',
    onSecondaryContainer: '#1f3000',
    tertiary: '#9c0040',
    onTertiary: '#ffffff',
    tertiaryContainer: '#ff3370',
    onTertiaryContainer: '#3d0018',
    background: '#fff5f7',
    surface: '#fff5f7',
    surfaceDim: '#e0d0d5',
    surfaceContainerLow: '#faf0f3',
    surfaceContainer: '#f4e8ec',
    surfaceContainerHigh: '#eedde3',
    surfaceContainerHighest: '#e8d5da',
    onSurface: '#1c1b1b',
    onSurfaceVariant: '#4a1828',
    outline: '#803050',
    outlineVariant: '#e0b0c0',
    error: '#ba1a1a',
    onError: '#ffffff',
    border: '#1c1b1b',
  },

  mangoOscuro: {
    primary: '#e67e00',
    onPrimary: '#ffffff',
    primaryContainer: '#ffb830',
    onPrimaryContainer: '#3d2000',
    primaryFixed: '#ffe8b0',
    primaryFixedDim: '#ffcc70',
    secondary: '#2d3a8c',
    onSecondary: '#ffffff',
    secondaryContainer: '#8a98ff',
    onSecondaryContainer: '#0a1050',
    tertiary: '#7a5200',
    onTertiary: '#ffffff',
    tertiaryContainer: '#d4a020',
    onTertiaryContainer: '#2a1800',
    background: '#fdfaf0',
    surface: '#fdfaf0',
    surfaceDim: '#ddd8c0',
    surfaceContainerLow: '#f8f4e4',
    surfaceContainer: '#f2edd8',
    surfaceContainerHigh: '#ece7cc',
    surfaceContainerHighest: '#e6e1c0',
    onSurface: '#1c1b1b',
    onSurfaceVariant: '#4a3810',
    outline: '#7a6028',
    outlineVariant: '#d4c090',
    error: '#ba1a1a',
    onError: '#ffffff',
    border: '#1c1b1b',
  },

  tamarindo: {
    primary: '#8b1a1a',
    onPrimary: '#ffffff',
    primaryContainer: '#c0392b',
    onPrimaryContainer: '#ffffff',
    primaryFixed: '#fde8d8',
    primaryFixedDim: '#f0b090',
    secondary: '#b5541c',
    onSecondary: '#ffffff',
    secondaryContainer: '#e8a87c',
    onSecondaryContainer: '#3d1500',
    tertiary: '#7a2a10',
    onTertiary: '#ffffff',
    tertiaryContainer: '#d47050',
    onTertiaryContainer: '#2a0800',
    background: '#fdf8f0',
    surface: '#fdf8f0',
    surfaceDim: '#ddd4c8',
    surfaceContainerLow: '#f8f2e8',
    surfaceContainer: '#f2ebe0',
    surfaceContainerHigh: '#ece4d6',
    surfaceContainerHighest: '#e6dccc',
    onSurface: '#1c1b1b',
    onSurfaceVariant: '#4a2818',
    outline: '#7a5040',
    outlineVariant: '#d4b0a0',
    error: '#ba1a1a',
    onError: '#ffffff',
    border: '#1c1b1b',
  },

  aguacate: {
    primary: '#1a7a00',
    onPrimary: '#ffffff',
    primaryContainer: '#4dcc00',
    onPrimaryContainer: '#0d3300',
    primaryFixed: '#d4ffc0',
    primaryFixedDim: '#a8f070',
    secondary: '#6600cc',
    onSecondary: '#ffffff',
    secondaryContainer: '#cc99ff',
    onSecondaryContainer: '#2d0066',
    tertiary: '#3d7a00',
    onTertiary: '#ffffff',
    tertiaryContainer: '#a0e040',
    onTertiaryContainer: '#1a3300',
    background: '#f5fff0',
    surface: '#f5fff0',
    surfaceDim: '#d8e8d0',
    surfaceContainerLow: '#f0fcea',
    surfaceContainer: '#e8f8e0',
    surfaceContainerHigh: '#e0f0d8',
    surfaceContainerHighest: '#d8e8d0',
    onSurface: '#1c1b1b',
    onSurfaceVariant: '#2d4020',
    outline: '#507040',
    outlineVariant: '#b0d8a0',
    error: '#ba1a1a',
    onError: '#ffffff',
    border: '#1c1b1b',
  },

  cafe: {
    primary: '#5c3317',
    onPrimary: '#ffffff',
    primaryContainer: '#a0622a',
    onPrimaryContainer: '#ffffff',
    primaryFixed: '#f0d8c0',
    primaryFixedDim: '#d4a878',
    secondary: '#8b6914',
    onSecondary: '#ffffff',
    secondaryContainer: '#d4aa40',
    onSecondaryContainer: '#2a1e00',
    tertiary: '#3d2210',
    onTertiary: '#ffffff',
    tertiaryContainer: '#8b6040',
    onTertiaryContainer: '#ffffff',
    background: '#fdf8f4',
    surface: '#fdf8f4',
    surfaceDim: '#ddd0c0',
    surfaceContainerLow: '#f8f0e4',
    surfaceContainer: '#f2e8d8',
    surfaceContainerHigh: '#ece0cc',
    surfaceContainerHighest: '#e6d8c0',
    onSurface: '#1c1b1b',
    onSurfaceVariant: '#4a3020',
    outline: '#7a5838',
    outlineVariant: '#d4b898',
    error: '#ba1a1a',
    onError: '#ffffff',
    border: '#1c1b1b',
  },

  oceano: {
    primary: '#005b99',
    onPrimary: '#ffffff',
    primaryContainer: '#0090d4',
    onPrimaryContainer: '#ffffff',
    primaryFixed: '#c8e8ff',
    primaryFixedDim: '#80c8f0',
    secondary: '#006b6b',
    onSecondary: '#ffffff',
    secondaryContainer: '#00c4c4',
    onSecondaryContainer: '#002828',
    tertiary: '#004080',
    onTertiary: '#ffffff',
    tertiaryContainer: '#4090cc',
    onTertiaryContainer: '#ffffff',
    background: '#f0f8ff',
    surface: '#f0f8ff',
    surfaceDim: '#c8d8e8',
    surfaceContainerLow: '#eaf4fc',
    surfaceContainer: '#e0eef8',
    surfaceContainerHigh: '#d6e8f4',
    surfaceContainerHighest: '#cce0f0',
    onSurface: '#1c1b1b',
    onSurfaceVariant: '#183050',
    outline: '#3860a0',
    outlineVariant: '#a0c0e0',
    error: '#ba1a1a',
    onError: '#ffffff',
    border: '#1c1b1b',
  },
};

export const THEME_META: Record<ThemeName, { label: string; swatches: [string, string, string] }> = {
  brasa:        { label: 'Brasa',          swatches: ['#c03a00', '#00d4b8', '#fdf7f5'] },
  negroni:      { label: 'Negroni',        swatches: ['#c44b00', '#1a1008', '#c9a227'] },
  guayaba:      { label: 'Guayaba',        swatches: ['#e8325a', '#0d5c6e', '#fff5f7'] },
  mezcal:       { label: 'Mezcal',         swatches: ['#9c5a00', '#3d6b2a', '#fdf8ee'] },
  ultravioleta: { label: 'Ultravioleta',   swatches: ['#3d00cc', '#cc4400', '#f8f5ff'] },
  calle:        { label: 'Calle',          swatches: ['#c9a800', '#1a1a2e', '#e94560'] },
  fresaPicante: { label: 'Fresa Picante',  swatches: ['#d4004c', '#5a8c00', '#fff5f7'] },
  mangoOscuro:  { label: 'Mango Oscuro',   swatches: ['#e67e00', '#2d3a8c', '#fdfaf0'] },
  tamarindo:    { label: 'Tamarindo',      swatches: ['#8b1a1a', '#b5541c', '#fdf8f0'] },
  aguacate:     { label: 'Aguacate',       swatches: ['#1a7a00', '#6600cc', '#f5fff0'] },
  cafe:         { label: 'Café',           swatches: ['#5c3317', '#8b6914', '#fdf8f4'] },
  oceano:       { label: 'Océano',         swatches: ['#005b99', '#006b6b', '#f0f8ff'] },
};
